config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @book.user_id = current_user.id
    @book.save
      redirect_to book_path(@book.id)
    # else
    #   render 'books/index'
    # end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
  end

  def destroy
    book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users =User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td><%= link_to attachment_image_tag(book.user,:profile_image, :fill, 50, 50, fallback: "no_image.jpg"),user_path(book.user) %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-6 offset-lg-3">
      <h1>Editing Book</h1>
        <%= form_with model:@book, local:true do |f| %>
        <div class="mt-3 mb-2">Title</div>
          <%= f.text_field :title, :size=>"50" %>
          <div class="mt-3 mb-2">Opinion</div>
          <%= f.text_area :body, :size=> "50x5" %>
          <div class="mt-3"><%= f.submit 'Update Book', class: 'btn btn-success' %></div>
        <% end %>
        <%=link_to "Show", book_path(@book.id) %>
        <%#= link_to "Back",
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mt-3">
      <%= render 'users/user', user: @user, book: @book %>
    </div>
    <div class="col-lg-7 offset-lg-1 mt-3">
      <%= render 'books/books', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mt-3">
      <%= render 'users/user', user: @user ,book: @book  %>
    </div>
    <div class="col-lg-7 offset-lg-1 mt-3">
      <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to attachment_image_tag(@user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"),user_path(@user.id) %><br>
                <%= link_to @user.name, user_path(@user.id) %>
              </td>
              <td><%= link_to @book.title,book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@user.id), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to "Destroy",book_path(@book),method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: '本当に削除しますか？'} %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row justify-content-center mt-3">
    <h1>Welcome to <b><i class="fas fa-book"></i>Bookers</b>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<body>
  <div class="container">
    <div class="row justify-content-center mt-3">
      <h1>welcome to <b><i class="fas fa-book"></i>Bookers</b> !!</h1>
    </div>
    <div class="row justify-content-center">
      <p>In <i class="fas fa-book"></i>Bookers,<br>
      you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!</p>
    </div>
    <div class="row d-flex justify-content-center">
      <%= link_to 'Log in', new_user_session_path,class: 'btn btn-info btn-sm w-50' %>
    </div>
    <div class="row d-flex justify-content-center mt-3">
      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm w-50" %>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ad383b9fb6.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-light p-3">

        <ul class="navbar-nav ml-auto" style="list-style: none; padding-left: 0;">
          <% if user_signed_in? %>
            <li class="mr-4"><%= link_to "Home", root_path, class: 'text-white' %></li>
            <li class="mr-4"><%= link_to "Users", users_path, class: 'text-white' %></li>
            <li class="mr-4"><%= link_to "Books", books_path, class: 'text-white' %></li>
            <li class="mr-5"><%= link_to "logout", destroy_user_session_path, method: :delete, class: 'text-white' %></li>
          <% else %>
            <li class="mr-4"><%= link_to "Home", root_path, class: 'text-white' %></li>
            <li class="mr-4"><%= link_to "About", homes_about_path,class: 'text-white' %></li>
            <li class="mr-4"><%= link_to "sign up", new_user_registration_path, class: 'text-white' %></li>
            <li class="mr-5"><%= link_to "login", new_user_session_path, class: 'text-white' %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<h2>User Info</h2>
<div class="my-3"><%= attachment_image_tag user, :profile_image, :fill, 80, 80, fallback: "no_image.jpg" %></div>
  <table class="table">
    <tbody>
      <tr>
        <td>name</td>
        <td><%= current_user.name %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td><%= current_user.introduction %></td>
      </tr>
    </tbody>
  </table>
<%= link_to '' , edit_user_path(user.id), class: "fas fa-user-cog btn btn-outline-secondary mx-auto d-block btn-sm" %>

<h2 class="mt-3">New Book</h2>
<%= form_with model:book, local:true do |f| %>
  <div class="mt-1 mb-1">Title</div>
    <%=f.text_field :title, :size=>"30" %>
  <div class="mt-3 mb-1">Opinion</div>
    <%= f.text_area :body, :size=>"30x4" %>
    <div class="mt-2"><%= f.submit 'Create Book',class: 'btn btn-success' %></div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-lg-3 mt-3">
      <h2>User Info</h2>
      <%= form_with model:@user, local:true do |f| %>
        <div class="my-2">Name</div>
        <%= text_field :name, id:"inputName" %>
        <div class="my-2">Image</div>
        <%= f.attachment_field :profile_image %>
        <div class="my-2">Introduction</div>
        <%= f.text_area :introduction %>
        <%= f.submit 'Update User', class: 'btn btn-secondary' %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mt-3">
      <%= render 'users/user', book: @book, user: @user %>
    </div>
    <div class="col-lg-7 offset-lg-1 mt-3">
      <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show',user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 mt-3">
      <%= render 'users/user', user:@user, book:@book %>
    </div>
    <div class="col-lg-7 offset-lg-1 mt-3">
      <%= render 'books/books', books: @books %>
    </div>
  </div>
</div>